######### 기본 설정 #########
spring:
  application:
    name: ai-project
  datasource:
        url: #[Database]://localhost:3306/[Database 스키마]#
        username: #[DB 아이디]#
        password: #[DB password]#
        driver-class-name: #[JDBC 드라이버]#

server:
  port: 8090

######### Swagger #########
springdoc:
  swagger-ui:
    use-root-path: true
    path: /ai
    tags-sorter: alpha
    operations-sorter: alpha
  cache:
    disabled: true