######### 기본 설정 #########
spring:
  application:
    name: ai-project
  datasource:
        url: jdbc:postgresql://localhost:5432/aiproject
        username: min
        password: 1234
        driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    database: postgresql
#    open-in-view: false
#    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true


server:
  port: 8092

######### Swagger #########
springdoc:
  swagger-ui:
    use-root-path: true
    path: /ai
    tags-sorter: alpha
    operations-sorter: alpha
  cache:
    disabled: true