######### 기본 설정 #########
spring:
  application:
    name: ai-project
  datasource:
        url: postgres://localhost:5432/aiproject
        username: min
        password: 1234
        driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    open-in-view: false
    generate-ddl: true


server:
  port: 8092

######### Swagger #########
springdoc:
  swagger-ui:
    use-root-path: true
    path: /ai
    tags-sorter: alpha
    operations-sorter: alpha
  cache:
    disabled: true