######### 기본 설정 #########
spring:
  application:
    name: ai-project
  datasource:
        url: postgres://localhost:5432/aiproject
        username: min
        password: 1234
        driver-class-name: #[JDBC 드라이버]#

server:
  port: 8090

######### Swagger #########
springdoc:
  swagger-ui:
    use-root-path: true
    path: /ai
    tags-sorter: alpha
    operations-sorter: alpha
  cache:
    disabled: true